name: hello-world-test
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jest and supertest
        run: npm install jest supertest --save-dev
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test 
